name: ecc_school_app_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  go_router: ^5.2.0
  json_annotation: ^4.7.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  flutter_html: ^2.2.1
  url_launcher: ^6.1.7
  table_calendar: ^3.0.8
  intl: ^0.17.0
  animations: ^2.0.7
  flutter_expandable_table: ^1.1.1
  flutter_custom_clippers: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  go_router_builder: ^1.0.15
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/introduction/
